# LAPACK Analysis Workspace
# 
# This workspace contains two main packages:
# - fortran-mapper/: Generic Fortran code analysis library
# - connectome/: LAPACK-specific connectome analysis tool
#
# To work with individual packages:
#   cd fortran-mapper && pip install -e .
#   cd connectome && pip install -e .

[tool.workspace]
members = [
    "fortran-mapper",
    "connectome"
]

# Development tools configuration for the entire workspace
[tool.ruff]
target-version = "py313"
line-length = 100
select = ["E", "F", "I", "N", "UP", "B", "C4", "SIM", "RUF"]

[tool.mypy]
python_version = "3.13"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true
