# LAPACK Analysis Workspace
# 
# This workspace contains two main packages:
# - fortran-mapper/: Generic Fortran code analysis library, with lapack hooks
# - connectome/: code agnostic connectivity analysis tool, with some lapack and fortran hooks

[tool.uv.workspace]
members = [
    "fortran-mapper",
    "fortran-mapper/hooks/lapack"
]

# Development tools configuration for the entire workspace
[tool.uv]
package = false
