# CMake generated Testfile for 
# Source directory: /home/batuhan/Projects/Gauntlet_Projects/lapack/worktrees/feature-sparse/SRC/SPARSE/TESTING
# Build directory: /home/batuhan/Projects/Gauntlet_Projects/lapack/worktrees/feature-sparse/build_sparse/TESTING
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(sparse_conversions "/home/batuhan/Projects/Gauntlet_Projects/lapack/worktrees/feature-sparse/build_sparse/TESTING/test_conversions")
set_tests_properties(sparse_conversions PROPERTIES  FAIL_REGULAR_EXPRESSION "FAILED|Error" PASS_REGULAR_EXPRESSION "ALL TESTS PASSED!" _BACKTRACE_TRIPLES "/home/batuhan/Projects/Gauntlet_Projects/lapack/worktrees/feature-sparse/SRC/SPARSE/TESTING/CMakeLists.txt;61;add_test;/home/batuhan/Projects/Gauntlet_Projects/lapack/worktrees/feature-sparse/SRC/SPARSE/TESTING/CMakeLists.txt;0;")
add_test(sparse_spmv "/home/batuhan/Projects/Gauntlet_Projects/lapack/worktrees/feature-sparse/build_sparse/TESTING/test_spmv")
set_tests_properties(sparse_spmv PROPERTIES  FAIL_REGULAR_EXPRESSION "FAILED|ERROR" PASS_REGULAR_EXPRESSION "Tests passed: [0-9]+ out of [0-9]+" _BACKTRACE_TRIPLES "/home/batuhan/Projects/Gauntlet_Projects/lapack/worktrees/feature-sparse/SRC/SPARSE/TESTING/CMakeLists.txt;64;add_test;/home/batuhan/Projects/Gauntlet_Projects/lapack/worktrees/feature-sparse/SRC/SPARSE/TESTING/CMakeLists.txt;0;")
add_test(sparse_matrices "/home/batuhan/Projects/Gauntlet_Projects/lapack/worktrees/feature-sparse/build_sparse/TESTING/test_matrices")
set_tests_properties(sparse_matrices PROPERTIES  FAIL_REGULAR_EXPRESSION "FAILED|Error" PASS_REGULAR_EXPRESSION "Tests passed: [0-9]+ out of [0-9]+" _BACKTRACE_TRIPLES "/home/batuhan/Projects/Gauntlet_Projects/lapack/worktrees/feature-sparse/SRC/SPARSE/TESTING/CMakeLists.txt;67;add_test;/home/batuhan/Projects/Gauntlet_Projects/lapack/worktrees/feature-sparse/SRC/SPARSE/TESTING/CMakeLists.txt;0;")
add_test(sparse_io "/home/batuhan/Projects/Gauntlet_Projects/lapack/worktrees/feature-sparse/build_sparse/TESTING/test_io")
set_tests_properties(sparse_io PROPERTIES  FAIL_REGULAR_EXPRESSION "FAILED|ERROR" PASS_REGULAR_EXPRESSION "Tests passed: [0-9]+ out of [0-9]+" _BACKTRACE_TRIPLES "/home/batuhan/Projects/Gauntlet_Projects/lapack/worktrees/feature-sparse/SRC/SPARSE/TESTING/CMakeLists.txt;73;add_test;/home/batuhan/Projects/Gauntlet_Projects/lapack/worktrees/feature-sparse/SRC/SPARSE/TESTING/CMakeLists.txt;0;")
add_test(sparse_advanced_operations "/home/batuhan/Projects/Gauntlet_Projects/lapack/worktrees/feature-sparse/build_sparse/TESTING/test_advanced_operations")
set_tests_properties(sparse_advanced_operations PROPERTIES  FAIL_REGULAR_EXPRESSION "failed|FAILED|Error" PASS_REGULAR_EXPRESSION "Tests: [0-9]+ passed" _BACKTRACE_TRIPLES "/home/batuhan/Projects/Gauntlet_Projects/lapack/worktrees/feature-sparse/SRC/SPARSE/TESTING/CMakeLists.txt;76;add_test;/home/batuhan/Projects/Gauntlet_Projects/lapack/worktrees/feature-sparse/SRC/SPARSE/TESTING/CMakeLists.txt;0;")
add_test(sparse_precision_variants "/home/batuhan/Projects/Gauntlet_Projects/lapack/worktrees/feature-sparse/build_sparse/TESTING/test_precision_variants")
set_tests_properties(sparse_precision_variants PROPERTIES  FAIL_REGULAR_EXPRESSION "failed|FAILED|Error" PASS_REGULAR_EXPRESSION "Total Tests: [0-9]+ passed" _BACKTRACE_TRIPLES "/home/batuhan/Projects/Gauntlet_Projects/lapack/worktrees/feature-sparse/SRC/SPARSE/TESTING/CMakeLists.txt;79;add_test;/home/batuhan/Projects/Gauntlet_Projects/lapack/worktrees/feature-sparse/SRC/SPARSE/TESTING/CMakeLists.txt;0;")
add_test(sparse_lapack_driver "/home/batuhan/Projects/Gauntlet_Projects/lapack/worktrees/feature-sparse/build_sparse/TESTING/dchkaa_sparse")
set_tests_properties(sparse_lapack_driver PROPERTIES  FAIL_REGULAR_EXPRESSION "FAILED|tests failed" PASS_REGULAR_EXPRESSION "All tests passed" _BACKTRACE_TRIPLES "/home/batuhan/Projects/Gauntlet_Projects/lapack/worktrees/feature-sparse/SRC/SPARSE/TESTING/CMakeLists.txt;83;add_test;/home/batuhan/Projects/Gauntlet_Projects/lapack/worktrees/feature-sparse/SRC/SPARSE/TESTING/CMakeLists.txt;0;")
add_test(sparse_error_exits "/home/batuhan/Projects/Gauntlet_Projects/lapack/worktrees/feature-sparse/build_sparse/TESTING/derrsp")
set_tests_properties(sparse_error_exits PROPERTIES  FAIL_REGULAR_EXPRESSION "failed the tests" PASS_REGULAR_EXPRESSION "routines passed the tests of the error exits" _BACKTRACE_TRIPLES "/home/batuhan/Projects/Gauntlet_Projects/lapack/worktrees/feature-sparse/SRC/SPARSE/TESTING/CMakeLists.txt;86;add_test;/home/batuhan/Projects/Gauntlet_Projects/lapack/worktrees/feature-sparse/SRC/SPARSE/TESTING/CMakeLists.txt;0;")
add_test(sparse_timing "/home/batuhan/Projects/Gauntlet_Projects/lapack/worktrees/feature-sparse/build_sparse/TESTING/dtimsp")
set_tests_properties(sparse_timing PROPERTIES  FAIL_REGULAR_EXPRESSION "ERROR|FAILED" PASS_REGULAR_EXPRESSION "Sparse Matrix Performance Tests" _BACKTRACE_TRIPLES "/home/batuhan/Projects/Gauntlet_Projects/lapack/worktrees/feature-sparse/SRC/SPARSE/TESTING/CMakeLists.txt;89;add_test;/home/batuhan/Projects/Gauntlet_Projects/lapack/worktrees/feature-sparse/SRC/SPARSE/TESTING/CMakeLists.txt;0;")
add_test(sparse_edge_cases "/home/batuhan/Projects/Gauntlet_Projects/lapack/worktrees/feature-sparse/build_sparse/TESTING/dspedge")
set_tests_properties(sparse_edge_cases PROPERTIES  FAIL_REGULAR_EXPRESSION "FAILED" PASS_REGULAR_EXPRESSION "All edge case tests PASSED" _BACKTRACE_TRIPLES "/home/batuhan/Projects/Gauntlet_Projects/lapack/worktrees/feature-sparse/SRC/SPARSE/TESTING/CMakeLists.txt;92;add_test;/home/batuhan/Projects/Gauntlet_Projects/lapack/worktrees/feature-sparse/SRC/SPARSE/TESTING/CMakeLists.txt;0;")
add_test(sparse_numerical_accuracy "/home/batuhan/Projects/Gauntlet_Projects/lapack/worktrees/feature-sparse/build_sparse/TESTING/dspnum")
set_tests_properties(sparse_numerical_accuracy PROPERTIES  FAIL_REGULAR_EXPRESSION "FAILED" PASS_REGULAR_EXPRESSION "All numerical accuracy tests PASSED" _BACKTRACE_TRIPLES "/home/batuhan/Projects/Gauntlet_Projects/lapack/worktrees/feature-sparse/SRC/SPARSE/TESTING/CMakeLists.txt;95;add_test;/home/batuhan/Projects/Gauntlet_Projects/lapack/worktrees/feature-sparse/SRC/SPARSE/TESTING/CMakeLists.txt;0;")
add_test(sparse_memory_management "/home/batuhan/Projects/Gauntlet_Projects/lapack/worktrees/feature-sparse/build_sparse/TESTING/dspmem")
set_tests_properties(sparse_memory_management PROPERTIES  FAIL_REGULAR_EXPRESSION "FAILED" PASS_REGULAR_EXPRESSION "All memory management tests PASSED" _BACKTRACE_TRIPLES "/home/batuhan/Projects/Gauntlet_Projects/lapack/worktrees/feature-sparse/SRC/SPARSE/TESTING/CMakeLists.txt;98;add_test;/home/batuhan/Projects/Gauntlet_Projects/lapack/worktrees/feature-sparse/SRC/SPARSE/TESTING/CMakeLists.txt;0;")
